In [35]:
!pip install pysus
!pip install pandas

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Requirement already satisfied: pysus in /usr/local/lib/python3.9/dist-packages (0.9.1)
Requirement already satisfied: numpy==1.23.2 in /usr/local/lib/python3.9/dist-packages (from pysus) (1.23.2)
Requirement already satisfied: pytz==2022.2.1 in /usr/local/lib/python3.9/dist-packages (from pysus) (2022.2.1)
Requirement already satisfied: dbfread==2.0.7 in /usr/local/lib/python3.9/dist-packages (from pysus) (2.0.7)
Requirement already satisfied: python-dateutil==2.8.2 in /usr/local/lib/python3.9/dist-packages (from pysus) (2.8.2)
Requirement already satisfied: loguru<0.7.0,>=0.6.0 in /usr/local/lib/python3.9/dist-packages (from pysus) (0.6.0)
Requirement already satisfied: jupyterlab<4.0.0,>=3.4.5 in /usr/local/lib/python3.9/dist-packages (from pysus) (3.6.3)
Requirement already satisfied: geobr<0.3.0,>=0.2.0 in /usr/local/lib/python3.9/dist-packages (from pysus) (0.2.0)
Requirement already satisfied: six==1.16.0 in /usr/local/lib/python3.9/dist-packages (from pysus) (1.16.0)
Requirement already satisfied: sqlalchemy<2.0.0 in /usr/local/lib/python3.9/dist-packages (from pysus) (1.4.47)
Requirement already satisfied: Unidecode<2.0.0,>=1.3.6 in /usr/local/lib/python3.9/dist-packages (from pysus) (1.3.6)
Requirement already satisfied: pyreaddbc==1.0.0 in /usr/local/lib/python3.9/dist-packages (from pysus) (1.0.0)
Requirement already satisfied: elasticsearch==7.16.2 in /usr/local/lib/python3.9/dist-packages (from pysus) (7.16.2)
Requirement already satisfied: pycparser==2.21 in /usr/local/lib/python3.9/dist-packages (from pysus) (2.21)
Requirement already satisfied: fastparquet<0.9.0,>=0.8.1 in /usr/local/lib/python3.9/dist-packages (from pysus) (0.8.3)
Requirement already satisfied: cffi==1.15.1 in /usr/local/lib/python3.9/dist-packages (from pysus) (1.15.1)
Requirement already satisfied: pandas==1.4.3 in /usr/local/lib/python3.9/dist-packages (from pysus) (1.4.3)
Requirement already satisfied: geocoder<2.0.0,>=1.38.1 in /usr/local/lib/python3.9/dist-packages (from pysus) (1.38.1)
Requirement already satisfied: ipykernel<7.0.0,>=6.22.0 in /usr/local/lib/python3.9/dist-packages (from pysus) (6.22.0)
Requirement already satisfied: tqdm==4.64.0 in /usr/local/lib/python3.9/dist-packages (from pysus) (4.64.0)
Requirement already satisfied: pyarrow>=11.0.0 in /usr/local/lib/python3.9/dist-packages (from pysus) (11.0.0)
Requirement already satisfied: wget<4.0,>=3.2 in /usr/local/lib/python3.9/dist-packages (from pysus) (3.2)
Requirement already satisfied: urllib3<2,>=1.21.1 in /usr/local/lib/python3.9/dist-packages (from elasticsearch==7.16.2->pysus) (1.26.15)
Requirement already satisfied: certifi in /usr/local/lib/python3.9/dist-packages (from elasticsearch==7.16.2->pysus) (2022.12.7)
Requirement already satisfied: cramjam>=2.3.0 in /usr/local/lib/python3.9/dist-packages (from fastparquet<0.9.0,>=0.8.1->pysus) (2.6.2)
Requirement already satisfied: packaging in /usr/local/lib/python3.9/dist-packages (from fastparquet<0.9.0,>=0.8.1->pysus) (23.0)
Requirement already satisfied: fsspec in /usr/local/lib/python3.9/dist-packages (from fastparquet<0.9.0,>=0.8.1->pysus) (2023.4.0)
Requirement already satisfied: geopandas<0.8.0,>=0.7.0 in /usr/local/lib/python3.9/dist-packages (from geobr<0.3.0,>=0.2.0->pysus) (0.7.0)
Requirement already satisfied: shapely<2.0.0,>=1.7.0 in /usr/local/lib/python3.9/dist-packages (from geobr<0.3.0,>=0.2.0->pysus) (1.8.5.post1)
Requirement already satisfied: ratelim in /usr/local/lib/python3.9/dist-packages (from geocoder<2.0.0,>=1.38.1->pysus) (0.1.6)
Requirement already satisfied: future in /usr/local/lib/python3.9/dist-packages (from geocoder<2.0.0,>=1.38.1->pysus) (0.18.3)
Requirement already satisfied: click in /usr/local/lib/python3.9/dist-packages (from geocoder<2.0.0,>=1.38.1->pysus) (8.1.3)
Requirement already satisfied: requests in /usr/local/lib/python3.9/dist-packages (from geocoder<2.0.0,>=1.38.1->pysus) (2.28.2)
Requirement already satisfied: pyzmq>=20 in /usr/local/lib/python3.9/dist-packages (from ipykernel<7.0.0,>=6.22.0->pysus) (23.2.1)
Requirement already satisfied: ipython>=7.23.1 in /usr/local/lib/python3.9/dist-packages (from ipykernel<7.0.0,>=6.22.0->pysus) (7.34.0)
Requirement already satisfied: jupyter-core!=5.0.*,>=4.12 in /usr/local/lib/python3.9/dist-packages (from ipykernel<7.0.0,>=6.22.0->pysus) (5.3.0)
Requirement already satisfied: nest-asyncio in /usr/local/lib/python3.9/dist-packages (from ipykernel<7.0.0,>=6.22.0->pysus) (1.5.6)
Requirement already satisfied: psutil in /usr/local/lib/python3.9/dist-packages (from ipykernel<7.0.0,>=6.22.0->pysus) (5.9.4)
Requirement already satisfied: traitlets>=5.4.0 in /usr/local/lib/python3.9/dist-packages (from ipykernel<7.0.0,>=6.22.0->pysus) (5.7.1)
Requirement already satisfied: jupyter-client>=6.1.12 in /usr/local/lib/python3.9/dist-packages (from ipykernel<7.0.0,>=6.22.0->pysus) (6.1.12)
Requirement already satisfied: tornado>=6.1 in /usr/local/lib/python3.9/dist-packages (from ipykernel<7.0.0,>=6.22.0->pysus) (6.2)
Requirement already satisfied: matplotlib-inline>=0.1 in /usr/local/lib/python3.9/dist-packages (from ipykernel<7.0.0,>=6.22.0->pysus) (0.1.6)
Requirement already satisfied: debugpy>=1.6.5 in /usr/local/lib/python3.9/dist-packages (from ipykernel<7.0.0,>=6.22.0->pysus) (1.6.6)
Requirement already satisfied: comm>=0.1.1 in /usr/local/lib/python3.9/dist-packages (from ipykernel<7.0.0,>=6.22.0->pysus) (0.1.3)
Requirement already satisfied: jupyter-server<3,>=1.16.0 in /usr/local/lib/python3.9/dist-packages (from jupyterlab<4.0.0,>=3.4.5->pysus) (1.23.6)
Requirement already satisfied: jinja2>=2.1 in /usr/local/lib/python3.9/dist-packages (from jupyterlab<4.0.0,>=3.4.5->pysus) (3.1.2)
Requirement already satisfied: tomli in /usr/local/lib/python3.9/dist-packages (from jupyterlab<4.0.0,>=3.4.5->pysus) (2.0.1)
Requirement already satisfied: jupyter-ydoc~=0.2.3 in /usr/local/lib/python3.9/dist-packages (from jupyterlab<4.0.0,>=3.4.5->pysus) (0.2.4)
Requirement already satisfied: jupyterlab-server~=2.19 in /usr/local/lib/python3.9/dist-packages (from jupyterlab<4.0.0,>=3.4.5->pysus) (2.22.1)
Requirement already satisfied: notebook<7 in /usr/local/lib/python3.9/dist-packages (from jupyterlab<4.0.0,>=3.4.5->pysus) (6.4.8)
Requirement already satisfied: jupyter-server-ydoc~=0.8.0 in /usr/local/lib/python3.9/dist-packages (from jupyterlab<4.0.0,>=3.4.5->pysus) (0.8.0)
Requirement already satisfied: nbclassic in /usr/local/lib/python3.9/dist-packages (from jupyterlab<4.0.0,>=3.4.5->pysus) (0.5.5)
Requirement already satisfied: greenlet!=0.4.17 in /usr/local/lib/python3.9/dist-packages (from sqlalchemy<2.0.0->pysus) (2.0.2)
Requirement already satisfied: pyproj>=2.2.0 in /usr/local/lib/python3.9/dist-packages (from geopandas<0.8.0,>=0.7.0->geobr<0.3.0,>=0.2.0->pysus) (3.5.0)
Requirement already satisfied: fiona in /usr/local/lib/python3.9/dist-packages (from geopandas<0.8.0,>=0.7.0->geobr<0.3.0,>=0.2.0->pysus) (1.9.3)
Requirement already satisfied: backcall in /usr/local/lib/python3.9/dist-packages (from ipython>=7.23.1->ipykernel<7.0.0,>=6.22.0->pysus) (0.2.0)
Requirement already satisfied: pickleshare in /usr/local/lib/python3.9/dist-packages (from ipython>=7.23.1->ipykernel<7.0.0,>=6.22.0->pysus) (0.7.5)
Requirement already satisfied: pygments in /usr/local/lib/python3.9/dist-packages (from ipython>=7.23.1->ipykernel<7.0.0,>=6.22.0->pysus) (2.14.0)
Requirement already satisfied: pexpect>4.3 in /usr/local/lib/python3.9/dist-packages (from ipython>=7.23.1->ipykernel<7.0.0,>=6.22.0->pysus) (4.8.0)
Requirement already satisfied: jedi>=0.16 in /usr/local/lib/python3.9/dist-packages (from ipython>=7.23.1->ipykernel<7.0.0,>=6.22.0->pysus) (0.18.2)
Requirement already satisfied: decorator in /usr/local/lib/python3.9/dist-packages (from ipython>=7.23.1->ipykernel<7.0.0,>=6.22.0->pysus) (4.4.2)
Requirement already satisfied: prompt-toolkit!=3.0.0,!=3.0.1,<3.1.0,>=2.0.0 in /usr/local/lib/python3.9/dist-packages (from ipython>=7.23.1->ipykernel<7.0.0,>=6.22.0->pysus) (3.0.38)
Requirement already satisfied: setuptools>=18.5 in /usr/local/lib/python3.9/dist-packages (from ipython>=7.23.1->ipykernel<7.0.0,>=6.22.0->pysus) (67.6.1)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.9/dist-packages (from jinja2>=2.1->jupyterlab<4.0.0,>=3.4.5->pysus) (2.1.2)
Requirement already satisfied: platformdirs>=2.5 in /usr/local/lib/python3.9/dist-packages (from jupyter-core!=5.0.*,>=4.12->ipykernel<7.0.0,>=6.22.0->pysus) (3.2.0)
Requirement already satisfied: prometheus-client in /usr/local/lib/python3.9/dist-packages (from jupyter-server<3,>=1.16.0->jupyterlab<4.0.0,>=3.4.5->pysus) (0.16.0)
Requirement already satisfied: websocket-client in /usr/local/lib/python3.9/dist-packages (from jupyter-server<3,>=1.16.0->jupyterlab<4.0.0,>=3.4.5->pysus) (1.5.1)
Requirement already satisfied: anyio<4,>=3.1.0 in /usr/local/lib/python3.9/dist-packages (from jupyter-server<3,>=1.16.0->jupyterlab<4.0.0,>=3.4.5->pysus) (3.6.2)
Requirement already satisfied: argon2-cffi in /usr/local/lib/python3.9/dist-packages (from jupyter-server<3,>=1.16.0->jupyterlab<4.0.0,>=3.4.5->pysus) (21.3.0)
Requirement already satisfied: nbformat>=5.2.0 in /usr/local/lib/python3.9/dist-packages (from jupyter-server<3,>=1.16.0->jupyterlab<4.0.0,>=3.4.5->pysus) (5.8.0)
Requirement already satisfied: terminado>=0.8.3 in /usr/local/lib/python3.9/dist-packages (from jupyter-server<3,>=1.16.0->jupyterlab<4.0.0,>=3.4.5->pysus) (0.17.1)
Requirement already satisfied: Send2Trash in /usr/local/lib/python3.9/dist-packages (from jupyter-server<3,>=1.16.0->jupyterlab<4.0.0,>=3.4.5->pysus) (1.8.0)
Requirement already satisfied: nbconvert>=6.4.4 in /usr/local/lib/python3.9/dist-packages (from jupyter-server<3,>=1.16.0->jupyterlab<4.0.0,>=3.4.5->pysus) (6.5.4)
Requirement already satisfied: ypy-websocket<0.9.0,>=0.8.2 in /usr/local/lib/python3.9/dist-packages (from jupyter-server-ydoc~=0.8.0->jupyterlab<4.0.0,>=3.4.5->pysus) (0.8.2)
Requirement already satisfied: jupyter-server-fileid<1,>=0.6.0 in /usr/local/lib/python3.9/dist-packages (from jupyter-server-ydoc~=0.8.0->jupyterlab<4.0.0,>=3.4.5->pysus) (0.9.0)
Requirement already satisfied: importlib-metadata>=3.6 in /usr/local/lib/python3.9/dist-packages (from jupyter-ydoc~=0.2.3->jupyterlab<4.0.0,>=3.4.5->pysus) (6.3.0)
Requirement already satisfied: y-py<0.6.0,>=0.5.3 in /usr/local/lib/python3.9/dist-packages (from jupyter-ydoc~=0.2.3->jupyterlab<4.0.0,>=3.4.5->pysus) (0.5.9)
Requirement already satisfied: babel>=2.10 in /usr/local/lib/python3.9/dist-packages (from jupyterlab-server~=2.19->jupyterlab<4.0.0,>=3.4.5->pysus) (2.12.1)
Requirement already satisfied: jsonschema>=4.17.3 in /usr/local/lib/python3.9/dist-packages (from jupyterlab-server~=2.19->jupyterlab<4.0.0,>=3.4.5->pysus) (4.17.3)
Requirement already satisfied: json5>=0.9.0 in /usr/local/lib/python3.9/dist-packages (from jupyterlab-server~=2.19->jupyterlab<4.0.0,>=3.4.5->pysus) (0.9.11)
Requirement already satisfied: ipython-genutils in /usr/local/lib/python3.9/dist-packages (from notebook<7->jupyterlab<4.0.0,>=3.4.5->pysus) (0.2.0)
Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.9/dist-packages (from requests->geocoder<2.0.0,>=1.38.1->pysus) (2.0.12)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.9/dist-packages (from requests->geocoder<2.0.0,>=1.38.1->pysus) (3.4)
Requirement already satisfied: notebook-shim>=0.1.0 in /usr/local/lib/python3.9/dist-packages (from nbclassic->jupyterlab<4.0.0,>=3.4.5->pysus) (0.2.2)
Requirement already satisfied: sniffio>=1.1 in /usr/local/lib/python3.9/dist-packages (from anyio<4,>=3.1.0->jupyter-server<3,>=1.16.0->jupyterlab<4.0.0,>=3.4.5->pysus) (1.3.0)
Requirement already satisfied: zipp>=0.5 in /usr/local/lib/python3.9/dist-packages (from importlib-metadata>=3.6->jupyter-ydoc~=0.2.3->jupyterlab<4.0.0,>=3.4.5->pysus) (3.15.0)
Requirement already satisfied: parso<0.9.0,>=0.8.0 in /usr/local/lib/python3.9/dist-packages (from jedi>=0.16->ipython>=7.23.1->ipykernel<7.0.0,>=6.22.0->pysus) (0.8.3)
Requirement already satisfied: pyrsistent!=0.17.0,!=0.17.1,!=0.17.2,>=0.14.0 in /usr/local/lib/python3.9/dist-packages (from jsonschema>=4.17.3->jupyterlab-server~=2.19->jupyterlab<4.0.0,>=3.4.5->pysus) (0.19.3)
Requirement already satisfied: attrs>=17.4.0 in /usr/local/lib/python3.9/dist-packages (from jsonschema>=4.17.3->jupyterlab-server~=2.19->jupyterlab<4.0.0,>=3.4.5->pysus) (22.2.0)
Requirement already satisfied: jupyter-events>=0.5.0 in /usr/local/lib/python3.9/dist-packages (from jupyter-server-fileid<1,>=0.6.0->jupyter-server-ydoc~=0.8.0->jupyterlab<4.0.0,>=3.4.5->pysus) (0.6.3)
Requirement already satisfied: entrypoints>=0.2.2 in /usr/local/lib/python3.9/dist-packages (from nbconvert>=6.4.4->jupyter-server<3,>=1.16.0->jupyterlab<4.0.0,>=3.4.5->pysus) (0.4)
Requirement already satisfied: lxml in /usr/local/lib/python3.9/dist-packages (from nbconvert>=6.4.4->jupyter-server<3,>=1.16.0->jupyterlab<4.0.0,>=3.4.5->pysus) (4.9.2)
Requirement already satisfied: beautifulsoup4 in /usr/local/lib/python3.9/dist-packages (from nbconvert>=6.4.4->jupyter-server<3,>=1.16.0->jupyterlab<4.0.0,>=3.4.5->pysus) (4.11.2)
Requirement already satisfied: nbclient>=0.5.0 in /usr/local/lib/python3.9/dist-packages (from nbconvert>=6.4.4->jupyter-server<3,>=1.16.0->jupyterlab<4.0.0,>=3.4.5->pysus) (0.7.3)
Requirement already satisfied: tinycss2 in /usr/local/lib/python3.9/dist-packages (from nbconvert>=6.4.4->jupyter-server<3,>=1.16.0->jupyterlab<4.0.0,>=3.4.5->pysus) (1.2.1)
Requirement already satisfied: bleach in /usr/local/lib/python3.9/dist-packages (from nbconvert>=6.4.4->jupyter-server<3,>=1.16.0->jupyterlab<4.0.0,>=3.4.5->pysus) (6.0.0)
Requirement already satisfied: pandocfilters>=1.4.1 in /usr/local/lib/python3.9/dist-packages (from nbconvert>=6.4.4->jupyter-server<3,>=1.16.0->jupyterlab<4.0.0,>=3.4.5->pysus) (1.5.0)
Requirement already satisfied: defusedxml in /usr/local/lib/python3.9/dist-packages (from nbconvert>=6.4.4->jupyter-server<3,>=1.16.0->jupyterlab<4.0.0,>=3.4.5->pysus) (0.7.1)
Requirement already satisfied: jupyterlab-pygments in /usr/local/lib/python3.9/dist-packages (from nbconvert>=6.4.4->jupyter-server<3,>=1.16.0->jupyterlab<4.0.0,>=3.4.5->pysus) (0.2.2)
Requirement already satisfied: mistune<2,>=0.8.1 in /usr/local/lib/python3.9/dist-packages (from nbconvert>=6.4.4->jupyter-server<3,>=1.16.0->jupyterlab<4.0.0,>=3.4.5->pysus) (0.8.4)
Requirement already satisfied: fastjsonschema in /usr/local/lib/python3.9/dist-packages (from nbformat>=5.2.0->jupyter-server<3,>=1.16.0->jupyterlab<4.0.0,>=3.4.5->pysus) (2.16.3)
Requirement already satisfied: ptyprocess>=0.5 in /usr/local/lib/python3.9/dist-packages (from pexpect>4.3->ipython>=7.23.1->ipykernel<7.0.0,>=6.22.0->pysus) (0.7.0)
Requirement already satisfied: wcwidth in /usr/local/lib/python3.9/dist-packages (from prompt-toolkit!=3.0.0,!=3.0.1,<3.1.0,>=2.0.0->ipython>=7.23.1->ipykernel<7.0.0,>=6.22.0->pysus) (0.2.6)
Requirement already satisfied: aiosqlite<1,>=0.17.0 in /usr/local/lib/python3.9/dist-packages (from ypy-websocket<0.9.0,>=0.8.2->jupyter-server-ydoc~=0.8.0->jupyterlab<4.0.0,>=3.4.5->pysus) (0.18.0)
Requirement already satisfied: aiofiles<23,>=22.1.0 in /usr/local/lib/python3.9/dist-packages (from ypy-websocket<0.9.0,>=0.8.2->jupyter-server-ydoc~=0.8.0->jupyterlab<4.0.0,>=3.4.5->pysus) (22.1.0)
Requirement already satisfied: argon2-cffi-bindings in /usr/local/lib/python3.9/dist-packages (from argon2-cffi->jupyter-server<3,>=1.16.0->jupyterlab<4.0.0,>=3.4.5->pysus) (21.2.0)
Requirement already satisfied: cligj>=0.5 in /usr/local/lib/python3.9/dist-packages (from fiona->geopandas<0.8.0,>=0.7.0->geobr<0.3.0,>=0.2.0->pysus) (0.7.2)
Requirement already satisfied: munch>=2.3.2 in /usr/local/lib/python3.9/dist-packages (from fiona->geopandas<0.8.0,>=0.7.0->geobr<0.3.0,>=0.2.0->pysus) (2.5.0)
Requirement already satisfied: click-plugins>=1.0 in /usr/local/lib/python3.9/dist-packages (from fiona->geopandas<0.8.0,>=0.7.0->geobr<0.3.0,>=0.2.0->pysus) (1.1.1)
Requirement already satisfied: rfc3986-validator>=0.1.1 in /usr/local/lib/python3.9/dist-packages (from jupyter-events>=0.5.0->jupyter-server-fileid<1,>=0.6.0->jupyter-server-ydoc~=0.8.0->jupyterlab<4.0.0,>=3.4.5->pysus) (0.1.1)
Requirement already satisfied: python-json-logger>=2.0.4 in /usr/local/lib/python3.9/dist-packages (from jupyter-events>=0.5.0->jupyter-server-fileid<1,>=0.6.0->jupyter-server-ydoc~=0.8.0->jupyterlab<4.0.0,>=3.4.5->pysus) (2.0.7)
Requirement already satisfied: rfc3339-validator in /usr/local/lib/python3.9/dist-packages (from jupyter-events>=0.5.0->jupyter-server-fileid<1,>=0.6.0->jupyter-server-ydoc~=0.8.0->jupyterlab<4.0.0,>=3.4.5->pysus) (0.1.4)
Requirement already satisfied: pyyaml>=5.3 in /usr/local/lib/python3.9/dist-packages (from jupyter-events>=0.5.0->jupyter-server-fileid<1,>=0.6.0->jupyter-server-ydoc~=0.8.0->jupyterlab<4.0.0,>=3.4.5->pysus) (6.0)
Requirement already satisfied: soupsieve>1.2 in /usr/local/lib/python3.9/dist-packages (from beautifulsoup4->nbconvert>=6.4.4->jupyter-server<3,>=1.16.0->jupyterlab<4.0.0,>=3.4.5->pysus) (2.4)
Requirement already satisfied: webencodings in /usr/local/lib/python3.9/dist-packages (from bleach->nbconvert>=6.4.4->jupyter-server<3,>=1.16.0->jupyterlab<4.0.0,>=3.4.5->pysus) (0.5.1)
Requirement already satisfied: jsonpointer>1.13 in /usr/local/lib/python3.9/dist-packages (from jsonschema>=4.17.3->jupyterlab-server~=2.19->jupyterlab<4.0.0,>=3.4.5->pysus) (2.3)
Requirement already satisfied: webcolors>=1.11 in /usr/local/lib/python3.9/dist-packages (from jsonschema>=4.17.3->jupyterlab-server~=2.19->jupyterlab<4.0.0,>=3.4.5->pysus) (1.13)
Requirement already satisfied: isoduration in /usr/local/lib/python3.9/dist-packages (from jsonschema>=4.17.3->jupyterlab-server~=2.19->jupyterlab<4.0.0,>=3.4.5->pysus) (20.11.0)
Requirement already satisfied: fqdn in /usr/local/lib/python3.9/dist-packages (from jsonschema>=4.17.3->jupyterlab-server~=2.19->jupyterlab<4.0.0,>=3.4.5->pysus) (1.5.1)
Requirement already satisfied: uri-template in /usr/local/lib/python3.9/dist-packages (from jsonschema>=4.17.3->jupyterlab-server~=2.19->jupyterlab<4.0.0,>=3.4.5->pysus) (1.2.0)
Requirement already satisfied: arrow>=0.15.0 in /usr/local/lib/python3.9/dist-packages (from isoduration->jsonschema>=4.17.3->jupyterlab-server~=2.19->jupyterlab<4.0.0,>=3.4.5->pysus) (1.2.3)
Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Requirement already satisfied: pandas in /usr/local/lib/python3.9/dist-packages (1.4.3)
Requirement already satisfied: numpy>=1.18.5 in /usr/local/lib/python3.9/dist-packages (from pandas) (1.23.2)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.9/dist-packages (from pandas) (2022.2.1)
Requirement already satisfied: python-dateutil>=2.8.1 in /usr/local/lib/python3.9/dist-packages (from pandas) (2.8.2)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.9/dist-packages (from python-dateutil>=2.8.1->pandas) (1.16.0)

In [36]:
import pandas as pd 
from pysus.online_data.SIH import download

In [66]:
vars = ['N_AIH','IDADE','SEXO','UF_ZI','NUM_FILHOS','INSTRU','MORTE','CID_MORTE','DIAS_PERM','DIAG_PRINC','DIAG_SECUN','DT_INTER','ANO_CMPT','MES_CMPT','MARCA_UTI','UTI_MES_TO','INFEHOPS']
meses = [1,2,3,4,5,6,7,8,9,10,11,12]
estado = 'es'
anos = [2019,2020,2021]
cids = ['F32','F33','F48']
aux={}

In [ ]:
for ano in anos:
  for mes in meses:
      aux[mes, ano] = pd.read_parquet(download(estado, ano, mes))
      print(f"O Arquivo do Mês {mes} do Ano {ano} do Estado do {estado.upper()} foi Baixado!")

In [84]:
sih_es = pd.concat({k:pd.DataFrame.from_dict(v) for k, v in aux.items()}, axis=0).reset_index()
sih_es = sih_es.filter(vars)
sih_es.drop(['N_AIH','IDADE','SEXO','UF_ZI','NUM_FILHOS','INSTRU','MORTE','CID_MORTE','DIAS_PERM','DIAG_SECUN','DT_INTER','ANO_CMPT','MES_CMPT','MARCA_UTI','UTI_MES_TO'],  axis=1, inplace=True)

sih_es.shape

(737395, 1)

In [85]:
# visualização dos pacientes
sih_es

       DIAG_PRINC
0            S028
1            T841
2            S721
3            T813
4            S270
...           ...
737390       N838
737391       Z302
737392       Z302
737393       Z302
737394       O342

[737395 rows x 1 columns]

In [87]:
sih_es = sih_es[sih_es['DIAG_PRINC'].isin(cids)]
sih_es

Empty DataFrame
Columns: [DIAG_PRINC]
Index: []

In [ ]:
# visualizaçao das variaveis que não possuem nenhum valor
sih_es['NUM_FILHOS'].unique(), sih_es['INSTRU'].unique(), sih_es['CID_MORTE'].unique(), sih_es['DIAG_SECUN'].unique()

In [ ]:
# excluindo variaveis que não possuem valores 
sih_es.drop(['NUM_FILHOS', 'INSTRU', 'CID_MORTE','DIAG_SECUN'], axis=1, inplace=True)

In [ ]:
sih_es

,N_AIH,IDADE,SEXO,UF_ZI,MORTE,DIAS_PERM,DIAG_PRINC,DT_INTER,ANO_CMPT,MES_CMPT,MARCA_UTI,UTI_MES_TO
0,3219102131091,30,3,320000,0,5,F33,20190826,2019,9,0,0
1,3219102109795,30,3,320000,0,2,F33,20190901,2019,9,0,0
2,3219102153509,24,3,320000,0,3,F33,20190910,2019,10,0,0
3,3220101533792,38,3,320000,0,1,F33,20200301,2020,4,0,0
4,3220101038627,19,1,320480,0,1,F32,20200820,2020,8,0,0
5,3220100474503,18,3,320190,0,3,F33,20200825,2020,9,0,0
6,3221101002911,40,3,320470,0,0,F32,20211119,2021,11,0,0

In [ ]:
# TRANSFORMAÇÃO

#  número da N_AIH - transformando em string e atribuindo como index
sih_es['N_AIH'] = sih_es['N_AIH'].astype(str)
sih_es.set_index(['N_AIH'], inplace=True)

In [ ]:
sih_es

,IDADE,SEXO,UF_ZI,MORTE,DIAS_PERM,DIAG_PRINC,DT_INTER,ANO_CMPT,MES_CMPT,MARCA_UTI,UTI_MES_TO
N_AIH,,,,,,,,,,,
3219102131091,30,3,320000,0,5,F33,20190826,2019,9,0,0
3219102109795,30,3,320000,0,2,F33,20190901,2019,9,0,0
3219102153509,24,3,320000,0,3,F33,20190910,2019,10,0,0
3220101533792,38,3,320000,0,1,F33,20200301,2020,4,0,0
3220101038627,19,1,320480,0,1,F32,20200820,2020,8,0,0
3220100474503,18,3,320190,0,3,F33,20200825,2020,9,0,0
3221101002911,40,3,320470,0,0,F32,20211119,2021,11,0,0

In [ ]:
# sexo - 1 = Masculino 3 = Feminino
sexo={1:'Masculino', 3:'Feminino'}
sih_es['SEXO'] = sih_es['SEXO'].replace(sexo)

In [ ]:
sih_es

,IDADE,SEXO,UF_ZI,MORTE,DIAS_PERM,DIAG_PRINC,DT_INTER,ANO_CMPT,MES_CMPT,MARCA_UTI,UTI_MES_TO
N_AIH,,,,,,,,,,,
3219102131091,30,Feminino,320000,0,5,F33,20190826,2019,9,0,0
3219102109795,30,Feminino,320000,0,2,F33,20190901,2019,9,0,0
3219102153509,24,Feminino,320000,0,3,F33,20190910,2019,10,0,0
3220101533792,38,Feminino,320000,0,1,F33,20200301,2020,4,0,0
3220101038627,19,Masculino,320480,0,1,F32,20200820,2020,8,0,0
3220100474503,18,Feminino,320190,0,3,F33,20200825,2020,9,0,0
3221101002911,40,Feminino,320470,0,0,F32,20211119,2021,11,0,0

In [ ]:
# backup
# sih_es = pd.concat({k:pd.DataFrame.from_dict(v) for k, v in aux.items()}, axis=0).reset_index()
# sih_es = sih_es.filter(vars)
# sih_es = sih_es[sih_es['DIAG_PRINC'].isin(cids)]
# sih_es.to_csv('sih_es.csv', index=False)        

# sih_es = pd.read_csv('sih_es.csv')
# sih_es.shape